apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stonesoup-int-srvc

resources:
  # Custom Resource Definitions
  - crds/appstudio.redhat.com_internalrequests.yaml
  - crds/appstudio.redhat.com_internalservicesconfigs.yaml
  #- crds/external-secrets.io_secretstores.yaml
  # External Secrets Resources
  - eso/secret-store.yaml
  # RBAC Resources
  - rbac/service_account.yaml
  - rbac/role.yaml
  - rbac/role_binding.yaml
  - rbac/leader_election_role.yaml
  - rbac/leader_election_role_binding.yaml
  - rbac/auth_proxy_client_clusterrole.yaml
  - rbac/auth_proxy_role.yaml
  - rbac/auth_proxy_role_binding.yaml
  - rbac/auth_proxy_service.yaml
  - rbac/internalrequest_editor_role.yaml
  - rbac/internalrequest_viewer_role.yaml
  - rbac/internalservicesconfig_editor_role.yaml
  - rbac/internalservicesconfig_viewer_role.yaml
  
  # CronJob Resources
  - cronjob/cleanup-internal-requests-pipelineruns.yaml 
